apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-config-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-config-service
  newName: ghcr.io/avollmaier/hypercrawler-config-service
  newTag: 2808464b8bf313f7511f37ef37e56cdc5e786074

replicas:
- count: 1
  name: hypercrawler-config-service
