apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercrawler-config-service
spec:
  template:
    spec:
      containers:
        - name: hypercrawler-config-service
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "100"
            - name: SPRING_PROFILES_ACTIVE
              value: prod