apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-supplier-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-supplier-service
  newName: ghcr.io/avollmaier/hypercrawler-supplier-service
  newTag: eb73f15cdaa53f3d32e461f16994e927e293d780

replicas:
- count: 1
  name: hypercrawler-supplier-service
