apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-supplier-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-supplier-service
  newName: ghcr.io/avollmaier/hypercrawler-supplier-service
  newTag: 714157a777cf3143b2e615ef45ef8ca35866f03d

replicas:
- count: 1
  name: hypercrawler-supplier-service
