apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercrawler-prioritizer-service
spec:
  template:
    spec:
      containers:
        - name: hypercrawler-prioritizer-service
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "100"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DISCOVERY_SERVICE_URL
              value: http://hypercrawler-discovery-service:9000/eureka/