apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-manager-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-manager-service
  newName: ghcr.io/avollmaier/hypercrawler-manager-service
  newTag: 44530e57d1ac1b6ce642cdee7b0fa91dbd8a90ed

replicas:
- count: 1
  name: hypercrawler-manager-service
