apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-manager-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-manager-service
  newName: ghcr.io/avollmaier/hypercrawler-manager-service
  newTag: eba646ca052f232e0bf919ed85a616c9674cea3a

replicas:
- count: 1
  name: hypercrawler-manager-service
