apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-manager-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-manager-service
  newName: ghcr.io/avollmaier/hypercrawler-manager-service
  newTag: d0c31db0206416f9c29c89baa74ab7d327839cfd

replicas:
- count: 1
  name: hypercrawler-manager-service
