apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-manager-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-manager-service
  newName: ghcr.io/avollmaier/hypercrawler-manager-service
  newTag: e93677accbe7c194655bcc3fac8c36e77dbd268b

replicas:
- count: 1
  name: hypercrawler-manager-service
