apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-manager-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-manager-service
  newName: ghcr.io/avollmaier/hypercrawler-manager-service
  newTag: 82d24a59eb77578139119a1994965d9c8a65c2c3

replicas:
- count: 1
  name: hypercrawler-manager-service
