apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-discovery-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-discovery-service
  newName: ghcr.io/avollmaier/hypercrawler-discovery-service
  newTag: b451e0fe428904c485b7976a1c2bf713f15aea3f

replicas:
- count: 1
  name: hypercrawler-discovery-service
