apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-edge-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-edge-service
  newName: ghcr.io/avollmaier/hypercrawler-edge-service
  newTag: 68d28e7fca2586f0fdb88b644979322ed1b480e4

replicas:
- count: 1
  name: hypercrawler-edge-service
