apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/avollmaier/hypercrawler-edge-service

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml

images:
- name: hypercrawler-edge-service
  newName: ghcr.io/avollmaier/hypercrawler-edge-service
  newTag: 14af8e8a1179ec34669f3fd72c3092eaa53f687a

replicas:
- count: 1
  name: hypercrawler-edge-service
