apiVersion: v1
kind: ConfigMap
metadata:
  name: hypercrawler-config
  labels:
    db: hypercrawler-neo4j

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercrawler-neo4j
  labels:
    db: hypercrawler-neo4j
spec:
  selector:
    matchLabels:
      db: hypercrawler-neo4j
  template:
    metadata:
      labels:
        db: hypercrawler-neo4j
    spec:
      containers:
        - name: hypercrawler-neo4j
          image: neo4j:latest
          env:
            - name: NEO4J_AUTH
              value: neo4j/password

---

apiVersion: v1
kind: Service
metadata:
  name: hypercrawler-neo4j
  labels:
    db: hypercrawler-neo4j
spec:
  type: ClusterIP
  selector:
    db: hypercrawler-neo4j
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
