apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    db: hypercrawler-rabbitmq
data:
  rabbitmq.conf: |
    default_user = admin
    default_pass = admin
    vm_memory_high_watermark.relative = 1.0
  enabled_plugins: |-
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_tracing].

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercrawler-rabbitmq
  labels:
    db: hypercrawler-rabbitmq
spec:
  selector:
    matchLabels:
      db: hypercrawler-rabbitmq
  template:
    metadata:
      labels:
        db: hypercrawler-rabbitmq
    spec:
      containers:
        - name: hypercrawler-rabbitmq
          image: rabbitmq:3.11-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config-volume
      volumes:
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-config

---

apiVersion: v1
kind: Service
metadata:
  name: hypercrawler-rabbitmq
  labels:
    db: hypercrawler-rabbitmq
spec:
  type: NodePort
  selector:
    db: hypercrawler-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672